data: robocup-train.yaml
epochs: 30
batch: 50
patience: 10
project: Robocup24 Detection Training
name: robocup3-1
optimizer: AdamW
cos_lr: true
close_mosaic: 5
lr0: 0.01
lrf: 0.01043
momentum: 0.937
weight_decay: 0.00052
warmup_epochs: 3.01614
warmup_momentum: 0.80829
warmup_bias_lr: 0.1
pretrained: true
box: 8.73982
cls: 0.60695
dfl: 1.67318
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.01773
hsv_s: 0.73164
hsv_v: 0.4
degrees: 0.0
translate: 0.09766
scale: 0.58711
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.46199
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0